<?php

namespace CodersLabBundle\Entity;


use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository {

    public function findByUser(User $user) {
        $ret = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('m')
            ->from('CodersLabBundle:Person', 'm')
            ->innerJoin('m.users', 'e')
            ->where('e.id = :userId')
            ->setParameter('userId', $user->getId())
            ->getQuery()
            ->getResult();

        return $ret;
    }
}